version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "python-pusimp/pusimp/.github/workflows/ci.yml"
