name: CI (against releases)

on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch:
  workflow_call:

jobs:
  test_0_1_0_installing_from_github:
    uses: python-pusimp/pusimp/.github/workflows/ci.yml@v0.1.0.post3
    with:
      ref: v0.1.0

  test_0_1_0_installing_from_pypi:
    uses: python-pusimp/pusimp/.github/workflows/ci.yml@v0.1.0.post3
    with:
      ref: v0.1.0
      index: PyPI
      index_version: 0.1.0

  test_0_1_1_installing_from_github:
    uses: python-pusimp/pusimp/.github/workflows/ci.yml@v0.1.1.post1
    with:
      ref: v0.1.1

  test_0_1_1_installing_from_pypi:
    uses: python-pusimp/pusimp/.github/workflows/ci.yml@v0.1.1.post1
    with:
      ref: v0.1.1
      index: PyPI
      index_version: 0.1.1

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'python-pusimp/pusimp' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@58c6022d9aeb22accfa8df9bf5b58c3d8867208c  # v1.0.0
        with:
          workflow-filename: ci_against_releases.yml
          days-elapsed: 50
